<?php

namespace Database\Seeders;

use App\Models\Cpl;
use App\Models\CplSndikti;
use Illuminate\Database\Seeder;

class CplSndiktiSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // A. SIKAP
            ['kode' => 'CPL-S01',  'kategori' => 'Sikap', 'deskripsi' => 'Bertakwa kepada Tuhan Yang Maha Esa dan mampu menunjukkan sikap religius.',                                                                                                                                                                                                                                                                 'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S02',  'kategori' => 'Sikap', 'deskripsi' => 'Menjunjung tinggi nilai kemanusiaan dalam menjalankan tugas berdasarkan agama, moral dan etika.',                                                                                                                                                                                                                                            'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S03',  'kategori' => 'Sikap', 'deskripsi' => 'Berkontribusi dalam peningkatan mutu kehidupan bermasyarakat, berbangsa, dan bernegara berdasarkan Pancasila.',                                                                                                                                                                                                                              'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S04',  'kategori' => 'Sikap', 'deskripsi' => 'Berperan sebagai warga negara yang bangga dan cinta tanah air, memiliki nasionalisme serta rasa tanggungjawab pada negara dan bangsa.',                                                                                                                                                                                                      'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S05',  'kategori' => 'Sikap', 'deskripsi' => 'Menghargai keanekaragaman budaya, pandangan, agama, dan kepercayaan, serta pendapat atau temuan orisinal orang lain.',                                                                                                                                                                                                                       'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S06',  'kategori' => 'Sikap', 'deskripsi' => 'Bekerja sama dan memiliki kepekaan sosial serta kepedulian terhadap masyarakat dan lingkungan.',                                                                                                                                                                                                                                             'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-S07',  'kategori' => 'Sikap', 'deskripsi' => 'Taat hukum dan disiplin dalam kehidupan bermasyarakat dan bernegara.',                                                                                                                                                                                                                                                                       'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S08',  'kategori' => 'Sikap', 'deskripsi' => 'Menginternalisasi nilai, norma, dan etika akademik.',                                                                                                                                                                                                                                                                                        'cpl_prodi' => 'CPL08'],
            ['kode' => 'CPL-S09',  'kategori' => 'Sikap', 'deskripsi' => 'Menunjukkan sikap bertanggungjawab atas pekerjaan di bidang keahliannya secara mandiri.',                                                                                                                                                                                                                                                    'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-S10',  'kategori' => 'Sikap', 'deskripsi' => 'Menginternalisasi semangat kemandirian, kejuangan, dan kewirausahaan.',                                                                                                                                                                                                                                                                      'cpl_prodi' => 'CPL10'],
            // B. KETERAMPILAN UMUM
            ['kode' => 'CPL-KU01', 'kategori' => 'KU',    'deskripsi' => 'Mampu menerapkan pemikiran logis, kritis, sistematis, dan inovatif dalam konteks pengembangan atau implementasi ilmu pengetahuan dan teknologi yang memperhatikan dan menerapkan nilai humaniora yang sesuai dengan bidang keahliannya.',                                                                                                      'cpl_prodi' => 'CPL09'],
            ['kode' => 'CPL-KU02', 'kategori' => 'KU',    'deskripsi' => 'Mampu menunjukkan kinerja mandiri, bermutu, dan terukur.',                                                                                                                                                                                                                                                                                   'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-KU03', 'kategori' => 'KU',    'deskripsi' => 'Mampu mengkaji implikasi pengembangan atau implementasi ilmu pengetahuan teknologi yang memperhatikan dan menerapkan nilai humaniora sesuai dengan keahliannya berdasarkan kaidah, tata cara dan etika ilmiah dalam rangka menghasilkan solusi, gagasan, desain atau kritik seni, menyusun deskripsi saintifik hasil kajiannya dalam bentuk skripsi atau laporan tugas akhir, dan mengunggahnya dalam laman perguruan tinggi.', 'cpl_prodi' => 'CPL09'],
            ['kode' => 'CPL-KU04', 'kategori' => 'KU',    'deskripsi' => 'Menyusun deskripsi saintifik hasil kajian tersebut di atas dalam bentuk skripsi atau laporan tugas akhir, dan mengunggahnya dalam laman perguruan tinggi.',                                                                                                                                                                                   'cpl_prodi' => 'CPL09'],
            ['kode' => 'CPL-KU05', 'kategori' => 'KU',    'deskripsi' => 'Mampu mengambil keputusan secara tepat dalam konteks penyelesaian masalah di bidang keahliannya, berdasarkan hasil analisis informasi dan data.',                                                                                                                                                                                             'cpl_prodi' => 'CPL09'],
            ['kode' => 'CPL-KU06', 'kategori' => 'KU',    'deskripsi' => 'Mampu memelihara dan mengembangkan jaringan kerja dengan pembimbing, kolega, sejawat baik di dalam maupun di luar lembaganya.',                                                                                                                                                                                                              'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-KU07', 'kategori' => 'KU',    'deskripsi' => 'Mampu bertanggungjawab atas pencapaian hasil kerja kelompok dan melakukan supervisi dan evaluasi terhadap penyelesaian pekerjaan yang ditugaskan kepada pekerja yang berada di bawah tanggungjawabnya.',                                                                                                                                      'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-KU08', 'kategori' => 'KU',    'deskripsi' => 'Mampu melakukan proses evaluasi diri terhadap kelompok kerja yang berada dibawah tanggung jawabnya, dan mampu mengelola pembelajaran secara mandiri.',                                                                                                                                                                                        'cpl_prodi' => 'CPL10'],
            ['kode' => 'CPL-KU09', 'kategori' => 'KU',    'deskripsi' => 'Mampu mendokumentasikan, menyimpan, mengamankan, dan menemukan kembali data untuk menjamin kesahihan dan mencegah plagiasi.',                                                                                                                                                                                                                'cpl_prodi' => 'CPL09'],
            ['kode' => 'CPL-KU10', 'kategori' => 'KU',    'deskripsi' => 'Berkomunikasi secara efektif dalam berbagai konteks profesional.',                                                                                                                                                                                                                                                                           'cpl_prodi' => 'CPL10'],
            // C. KETERAMPILAN KHUSUS
            ['kode' => 'CPL-KK01', 'kategori' => 'KK',    'deskripsi' => 'Mampu memahami, menganalisis, dan menilai konsep dasar dan peran sistem informasi dalam mengelola data dan memberikan rekomendasi pengambilan keputusan pada proses dan sistem organisasi.',                                                                                                                                                  'cpl_prodi' => 'CPL01'],
            ['kode' => 'CPL-KK02', 'kategori' => 'KK',    'deskripsi' => 'Mampu membangun, mengelola, menggunakan dan mengamankan database dengan alat dan teknik dalam sistem basis data yang akan menghasilkan model relasional.',                                                                                                                                                                                    'cpl_prodi' => 'CPL02'],
            ['kode' => 'CPL-KK03', 'kategori' => 'KK',    'deskripsi' => 'Mampu membuat perencanaan infrastruktur TI, arsitektur jaringan, layanan fisik dan cloud, menganalisa konsep identifikasi, otentikasi, otorisasi akses dalam konteks melindungi orang dan perangkat.',                                                                                                                                       'cpl_prodi' => 'CPL04'],
            ['kode' => 'CPL-KK04', 'kategori' => 'KK',    'deskripsi' => 'Mampu menerapkan metodologi pengembangan sistem informasi beserta alat pemodelannya meliputi pengembangan sistem berorientasi objek, system development life cycle (SDLC).',                                                                                                                                                                  'cpl_prodi' => 'CPL03'],
            ['kode' => 'CPL-KK05', 'kategori' => 'KK',    'deskripsi' => 'Mampu menerapkan dasar logika, prinsip matematika, ekspresi, aspek modular, linearitas dan non-linearitas struktur data pada pemrograman perangkat lunak.',                                                                                                                                                                                  'cpl_prodi' => 'CPL03'],
            ['kode' => 'CPL-KK06', 'kategori' => 'KK',    'deskripsi' => 'Mampu memahami, menerapkan kode etik dalam penggunaan informasi dan data pada perancangan, implementasi, dan penggunaan suatu sistem.',                                                                                                                                                                                                      'cpl_prodi' => 'CPL05'],
            ['kode' => 'CPL-KK07', 'kategori' => 'KK',    'deskripsi' => 'Memiliki kemampuan merencanakan, menerapkan, memelihara dan meningkatkan sistem informasi organisasi untuk mencapai tujuan dan sasaran organisasi yang strategis baik jangka pendek maupun jangka panjang.',                                                                                                                                  'cpl_prodi' => 'CPL06'],
            ['kode' => 'CPL-KK08', 'kategori' => 'KK',    'deskripsi' => 'Memiliki kemampuan untuk memantau, mengevaluasi dan mengendalikan sumberdaya sistem informasi untuk memastikan keselarasan, pencapaian dan sasaran strategis organisasi.',                                                                                                                                                                    'cpl_prodi' => 'CPL06'],
            ['kode' => 'CPL-KK09', 'kategori' => 'KK',    'deskripsi' => 'Mampu membangun perangkat lunak dalam sebuah proyek sistem informasi.',                                                                                                                                                                                                                                                                      'cpl_prodi' => 'CPL07'],
            // D. PENGETAHUAN
            ['kode' => 'CPL-P01',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami, menganalisis, dan menilai konsep dasar dan peran sistem informasi dalam mengelola data dan memberikan rekomendasi pengambilan keputusan pada proses dan sistem organisasi.',                                                                                                                                             'cpl_prodi' => 'CPL01'],
            ['kode' => 'CPL-P02',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan menjelaskan konsep basis data, struktur data dan visualisasi data secara menyeluruh.',                                                                                                                                                                                                                              'cpl_prodi' => 'CPL02'],
            ['kode' => 'CPL-P03',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan menjelaskan konsep infrastruktur TI, arsitektur jaringan, layanan fisik dan cloud untuk menganalisa konsep identifikasi, otentikasi, otorisasi akses dalam konteks melindungi orang dan perangkat.',                                                                                                                 'cpl_prodi' => 'CPL04'],
            ['kode' => 'CPL-P04',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan menjelaskan metodologi pengembangan sistem informasi mulai dari pengembangan sistem berorientasi objek, Software Development Life Cycle (SDLC), dan pengembangan agile.',                                                                                                                                             'cpl_prodi' => 'CPL03'],
            ['kode' => 'CPL-P05',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan menjelaskan dasar logika, prinsip matematika, ekspresi, aspek modular, linearitas dan non-linearitas struktur data pada perangkat lunak.',                                                                                                                                                                          'cpl_prodi' => 'CPL03'],
            ['kode' => 'CPL-P06',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan mengkaji dasar hukum kode etik dalam penggunaan informasi dan data pada perancangan, implementasi, dan penggunaan suatu sistem.',                                                                                                                                                                                    'cpl_prodi' => 'CPL05'],
            ['kode' => 'CPL-P07',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami dan menjelaskan konsep perencanaan strategis, resiko organisasi, serta kerangka kerja tata kelola sistem informasi.',                                                                                                                                                                                                   'cpl_prodi' => 'CPL06'],
            ['kode' => 'CPL-P08',  'kategori' => 'PP', 'deskripsi' => 'Mampu memahami konsep, teknik pada manajemen proyek untuk memenuhi business requirement berdasarkan kriteria pengambilan keputusan.',                                                                                                                                                                                                   'cpl_prodi' => 'CPL07'],
        ];

        $cplCache = Cpl::all()->keyBy('kode');

        foreach ($data as $item) {
            $cplProdi = $item['cpl_prodi'];
            unset($item['cpl_prodi']);

            $sndikti = CplSndikti::updateOrCreate(
                ['kode' => $item['kode']],
                ['kategori' => $item['kategori'], 'deskripsi' => $item['deskripsi']]
            );

            // Attach to CPL Prodi
            $cpl = $cplCache->get($cplProdi);
            if ($cpl) {
                $sndikti->cpls()->syncWithoutDetaching([$cpl->id]);
            }
        }
    }
}
